### ISSUE TITLE
Question about start.

### ISSUE THREAD

**Issue by acmgit** [APercy/b47_heli#3]
Should it to be so, when you start the heli and you go up, after a short time and you do nothing, the helicopter starts to drive backwards. The heli drive from time to time faster backwards, so it's very difficult to hold the helicopter on a course.

Greetings, Clyde.

**Comment by APercy** [comment]
I will debug it, thank you!
PS: I need you give me one at your server for some tests, you can destroy it after

**Comment by APercy** [comment]
I believe it is the wind acting over the flight, but I will test it more

**Comment by acmgit** [comment]
Of course, no problem, i will give you some with biofuel.

**Comment by acmgit** [comment]
Go on the server Zeitsprung from spawn the hill up to the house. Spawn 1. There you will find a blue chest, there are your helicopters and biofuel ;-).

**Comment by acmgit** [comment]
Hello Percy,
i've seen, you updated the b47, but the problem is the same.
Go up with the heli and do nothing, the heli drives self in a direction, without to do something.

**Comment by APercy** [comment]
okay, airutils updated again, try now :)
PS: the wind will affect anyway, but I limited the backwards movement

**Comment by acmgit** [comment]
Hello Percy, it's a little bit difficult to fly, but it seems now to work.
Thanks for fixing it ;-).

Greetings, Clyde.
